name: Build and Push Docker Image

on:
  create:
    tags:
      - 'v*'  # Also trigger the workflow when a new tag is pushed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensure full history for tags

      # Get the latest tag
      - name: Get latest tag
        id: get_tag
        run: echo "TAG_NAME=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to GitHub Container Registry
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build and push Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile  # Adjust path if your Dockerfile is in a different location
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/orcaslicer-novnc:latest
            ghcr.io/${{ github.repository_owner }}/orcaslicer-novnc:${{ env.TAG_NAME }}
