name: Tag latest

on:
  schedule:
    - cron: "0 1 * * *" # Every night at 2.=
  workflow_dispatch:
  
jobs:
  tag:
    runs-on: ubuntu-latest

    steps:
      - uses: sergeysova/jq-action@v2 # Needed for parsing the JSON of the Prusaslicer releases.
      - name: checkout repo content
        uses: actions/checkout@v2 # Checkout the repository content to GitHub's runner.
      - name: Tag the latest Orcaslicer if available
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          chmod +x ./tag_latest_orcaslicer.sh
          ./tag_latest_orcaslicer.sh
